apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cozypaws-ai-data
  namespace: cozypaws
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cozypaws-ai-models
  namespace: cozypaws
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
